"""
forensics/packet_logger.py

Purpose: Write full forensic PCAP files from live Scapy captures or from
         synthetic flow-event records generated by the detection pipeline.
         Each detection event is encoded into a minimal Ethernet/IP/TCP frame
         and appended to a rolling PCAP file that rotates automatically when
         it exceeds a size or age limit.

         Two modes:
           Live    — Scapy AsyncSniffer captures raw packets; saved verbatim.
           Synthetic — Detection events serialised as fake frames for forensic
                       audit trails when live capture is not available.

Inputs:  Raw Scapy packets (live mode) or detection event dicts (synthetic).
Outputs: PCAP files written to pcap/ directory with naming convention
         sentinel_<timestamp>_<session_id>.pcap.

Usage:
    from forensics.packet_logger import PacketLogger
    logger_ = PacketLogger()
    logger_.log_event({"src_ip": "1.2.3.4", "dst_port": 80, "payload": b"GET /"})
    logger_.flush()
    logger_.start_live_capture(interface="eth0")   # requires root / Scapy
"""

import logging
import socket
import struct
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from config import PCAP_DIR

logger = logging.getLogger(__name__)

# PCAP constants
_PCAP_MAGIC      = 0xA1B2C3D4
_PCAP_VERSION_MAJ = 2
_PCAP_VERSION_MIN = 4
_LINK_ETHERNET   = 1
_SNAPLEN         = 65535

# Rolling file limits
_MAX_FILE_BYTES  = 100 * 1024 * 1024   # 100 MB per file
_MAX_FILE_AGE_S  = 3600                 # 1 hour per file
_FLUSH_INTERVAL_S = 5                   # background flush cadence


# ---------------------------------------------------------------------------
# PCAP binary helpers
# ---------------------------------------------------------------------------

def _global_header() -> bytes:
    return struct.pack(
        "<IHHiIII",
        _PCAP_MAGIC,
        _PCAP_VERSION_MAJ, _PCAP_VERSION_MIN,
        0,          # thiszone
        0,          # sigfigs
        _SNAPLEN,
        _LINK_ETHERNET,
    )


def _packet_record(raw: bytes, ts: Optional[float] = None) -> bytes:
    ts     = ts or time.time()
    ts_sec = int(ts)
    ts_us  = int((ts - ts_sec) * 1_000_000)
    ln     = len(raw)
    return struct.pack("<IIII", ts_sec, ts_us, ln, ln) + raw


def _build_frame(
    src_ip:   str,
    dst_ip:   str,
    src_port: int,
    dst_port: int,
    payload:  bytes,
    flags:    int = 0x02,   # SYN by default
) -> bytes:
    """Assemble a fake Ethernet + IP + TCP frame for forensic logging."""
    # Ethernet header (src mac → dst mac, EtherType IPv4)
    eth = b"\xde\xad\xbe\xef\x00\x01" + b"\xff" * 6 + b"\x08\x00"

    try:
        src_packed = socket.inet_aton(src_ip)
    except OSError:
        src_packed = b"\x00\x00\x00\x00"
    try:
        dst_packed = socket.inet_aton(dst_ip)
    except OSError:
        dst_packed = b"\x7f\x00\x00\x01"

    ip_total = 20 + 20 + len(payload)
    ip_hdr = struct.pack(
        "!BBHHHBBH4s4s",
        0x45, 0,          # version+IHL, DSCP+ECN
        ip_total,
        0,                # identification
        0x4000,           # flags (DF), fragment offset
        64,               # TTL
        6,                # proto TCP
        0,                # checksum (not computed for forensic logs)
        src_packed,
        dst_packed,
    )

    tcp_hdr = struct.pack(
        "!HHIIBBHHH",
        src_port & 0xFFFF,
        dst_port & 0xFFFF,
        0,              # seq
        0,              # ack
        0x50,           # data offset (5 × 4 = 20)
        flags,
        65535,          # window
        0,              # checksum
        0,              # urgent pointer
    )

    return eth + ip_hdr + tcp_hdr + payload


# ---------------------------------------------------------------------------
# Rolling PCAP file handle
# ---------------------------------------------------------------------------

class _PcapFile:
    """Manages a single rolling PCAP file with size/age-based rotation."""

    def __init__(self, directory: Path, session_id: str) -> None:
        self._dir        = directory
        self._session_id = session_id
        self._fh         = None
        self._path:      Optional[Path] = None
        self._opened_at: float          = 0.0
        self._bytes      = 0
        self._lock       = threading.Lock()
        self._open_new()

    def _open_new(self) -> None:
        ts   = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S")
        name = f"sentinel_{ts}_{self._session_id[:8]}.pcap"
        self._path = self._dir / name
        try:
            self._fh       = open(self._path, "wb")   # noqa: WPS515
            self._fh.write(_global_header())
            self._fh.flush()
            self._opened_at = time.monotonic()
            self._bytes     = len(_global_header())
            logger.info("PacketLogger: opened %s", self._path)
        except OSError as exc:
            logger.error("Failed to open PCAP file %s: %s", self._path, exc)
            self._fh = None

    def write(self, raw: bytes, ts: Optional[float] = None) -> None:
        with self._lock:
            if self._fh is None:
                return
            record = _packet_record(raw, ts)
            try:
                self._fh.write(record)
                self._bytes += len(record)
            except OSError as exc:
                logger.error("PCAP write error: %s", exc)

    def flush(self) -> None:
        with self._lock:
            if self._fh:
                try:
                    self._fh.flush()
                except OSError:
                    pass

    def should_rotate(self) -> bool:
        age = time.monotonic() - self._opened_at
        return self._bytes >= _MAX_FILE_BYTES or age >= _MAX_FILE_AGE_S

    def rotate(self) -> Path:
        old_path = self._path
        with self._lock:
            if self._fh:
                try:
                    self._fh.close()
                except OSError:
                    pass
            self._open_new()
        logger.info("PacketLogger: rotated PCAP — closed %s", old_path)
        return old_path

    def close(self) -> None:
        with self._lock:
            if self._fh:
                try:
                    self._fh.flush()
                    self._fh.close()
                except OSError:
                    pass
                self._fh = None

    @property
    def path(self) -> Optional[Path]:
        return self._path

    @property
    def bytes_written(self) -> int:
        return self._bytes


# ---------------------------------------------------------------------------
# PacketLogger
# ---------------------------------------------------------------------------

class PacketLogger:
    """
    Forensic PCAP logger supporting live capture and event-based synthetic logging.

    Live mode    — Requires Scapy installed and root privileges.
                   Call start_live_capture(interface) to begin sniffing.
    Synthetic mode — Call log_event(event_dict) to record detection events
                     as forensic frame records regardless of Scapy availability.

    PCAP files are written to pcap/ and rotate at 100 MB or 1 hour.
    A background thread flushes the write buffer every 5 seconds.

    Parameters:
        pcap_dir   — directory for PCAP output (default config.PCAP_DIR)
        session_id — stable identifier for this capture session; auto-generated
                     if not provided.
    """

    def __init__(
        self,
        pcap_dir:   Optional[Path] = None,
        session_id: Optional[str]  = None,
    ) -> None:
        self._dir        = pcap_dir or PCAP_DIR
        self._session_id = session_id or uuid.uuid4().hex
        self._pcap       = _PcapFile(self._dir, self._session_id)
        self._packet_count   = 0
        self._sniffer        = None
        self._lock           = threading.Lock()
        self._stop_flush_evt = threading.Event()

        self._start_flush_thread()
        logger.info(
            "PacketLogger ready — session=%s, dir=%s",
            self._session_id[:8], self._dir,
        )

    # ------------------------------------------------------------------
    # Background flush
    # ------------------------------------------------------------------

    def _start_flush_thread(self) -> None:
        t = threading.Thread(
            target=self._flush_loop, daemon=True, name="pcap-flush"
        )
        t.start()

    def _flush_loop(self) -> None:
        while not self._stop_flush_evt.wait(_FLUSH_INTERVAL_S):
            self._pcap.flush()
            if self._pcap.should_rotate():
                self._pcap.rotate()

    # ------------------------------------------------------------------
    # Synthetic event logging
    # ------------------------------------------------------------------

    def log_event(self, event: dict, ts: Optional[float] = None) -> None:
        """
        Encode a detection event dict as a forensic PCAP frame record.

        The event dict should contain src_ip, dst_port, and optionally
        payload (bytes), src_port, dst_ip, attack_type.

        Inputs:
            event — detection event dict
            ts    — Unix timestamp override; uses current time if None
        """
        src_ip   = event.get("src_ip",   "0.0.0.0")
        dst_ip   = event.get("dst_ip",   "127.0.0.1")
        src_port = int(event.get("src_port", 0))
        dst_port = int(event.get("dst_port") or event.get("destination_port", 0))
        payload  = event.get("payload", b"")

        if isinstance(payload, str):
            payload = payload.encode("utf-8", errors="replace")
        if not isinstance(payload, (bytes, bytearray)):
            payload = b""

        # Embed attack_type as ASCII comment at start of payload for readability
        attack_type = event.get("attack_type", "")
        if attack_type:
            marker  = f"[SENTINEL:{attack_type}] ".encode()
            payload = marker + payload

        raw = _build_frame(src_ip, dst_ip, src_port, dst_port, payload)
        self._write_raw(raw, ts)

    def log_raw(self, raw: bytes, ts: Optional[float] = None) -> None:
        """
        Write a pre-built raw frame directly to the PCAP file.

        Inputs:  raw — complete Ethernet frame bytes
        """
        self._write_raw(raw, ts)

    def _write_raw(self, raw: bytes, ts: Optional[float]) -> None:
        with self._lock:
            self._pcap.write(raw, ts)
            self._packet_count += 1

    # ------------------------------------------------------------------
    # Live capture (Scapy)
    # ------------------------------------------------------------------

    def start_live_capture(
        self,
        interface: str = "eth0",
        bpf_filter: str = "",
        packet_count: int = 0,
    ) -> bool:
        """
        Start asynchronous live packet capture via Scapy.

        Requires Scapy to be installed and root/admin privileges.
        Packets are written verbatim to the rolling PCAP file.

        Inputs:
            interface    — network interface name (e.g. "eth0", "\\Device\\NPF_{...}")
            bpf_filter   — Berkeley Packet Filter expression (e.g. "tcp port 80")
            packet_count — stop after N packets; 0 = capture indefinitely
        Outputs: True if sniffer started; False if Scapy unavailable
        """
        try:
            from scapy.sendrecv import AsyncSniffer  # type: ignore
        except ImportError:
            logger.warning("Scapy not available — live capture disabled")
            return False

        def _handle(pkt):
            try:
                raw = bytes(pkt)
                self._write_raw(raw, float(pkt.time) if hasattr(pkt, "time") else None)
            except Exception as exc:
                logger.debug("Packet handler error: %s", exc)

        try:
            kwargs: dict = {
                "iface":   interface,
                "prn":     _handle,
                "store":   False,
            }
            if bpf_filter:
                kwargs["filter"] = bpf_filter
            if packet_count > 0:
                kwargs["count"] = packet_count

            self._sniffer = AsyncSniffer(**kwargs)
            self._sniffer.start()
            logger.info(
                "Live capture started on %s (filter=%r)",
                interface, bpf_filter or "none",
            )
            return True
        except Exception as exc:
            logger.error("Failed to start live capture on %s: %s", interface, exc)
            return False

    def stop_live_capture(self) -> None:
        """Stop the Scapy live capture sniffer if running."""
        if self._sniffer:
            try:
                self._sniffer.stop()
                logger.info("Live capture stopped")
            except Exception as exc:
                logger.warning("Sniffer stop error: %s", exc)
            self._sniffer = None

    # ------------------------------------------------------------------
    # Control
    # ------------------------------------------------------------------

    def flush(self) -> None:
        """Force a flush of the current PCAP write buffer."""
        self._pcap.flush()

    def rotate(self) -> Optional[Path]:
        """Force a PCAP file rotation. Returns the closed file path."""
        return self._pcap.rotate()

    def close(self) -> None:
        """Stop background threads and close the current PCAP file."""
        self._stop_flush_evt.set()
        self.stop_live_capture()
        self._pcap.flush()
        self._pcap.close()
        logger.info(
            "PacketLogger closed — %d packets written to %s",
            self._packet_count, self._pcap.path,
        )

    @property
    def current_file(self) -> Optional[Path]:
        return self._pcap.path

    @property
    def packet_count(self) -> int:
        return self._packet_count

    def summary(self) -> dict:
        return {
            "session_id":    self._session_id[:8],
            "current_file":  str(self._pcap.path),
            "packet_count":  self._packet_count,
            "bytes_written": self._pcap.bytes_written,
            "live_active":   self._sniffer is not None,
        }
